---
- name: 部署應用程式到邊緣裝置
  hosts: wsl_hosts
  become: false
  gather_facts: false

  tasks:
    # ----------------------------------------------------
    - name: 1. 確認裝置資訊
      debug:
        msg: "Deploying to {{ inventory_hostname }} with DEVICE_ID={{ DEVICE_ID }}, PORT={{ DEPLOY_PORT }}"

    # ----------------------------------------------------
    - name: 2. 拉取映像檔
      docker_image:
        name: "{{ REGISTRY_HOST_PORT }}/pc-hello-world:latest"
        source: pull

    # ----------------------------------------------------
#    - name: 3. 啟動容器
#      docker_container:
#        name: pc-hello-world
#        image: "{{ REGISTRY_HOST_PORT }}/pc-hello-world:latest"
#        state: started
#        restart_policy: always
#        env:
#          DEVICE_ID: "{{ DEVICE_ID }}"
#          LOG_LEVEL: "{{ LOG_LEVEL }}"
#        published_ports:
#          - "{{ DEPLOY_PORT }}:8080"
#          -

    # ----------------------------------------------------
#    - name: 3. 啟動容器 ( Compose )
#      community.docker.docker_compose:
#        project_src: "{{ playbook_dir }}/../docker/script"
#        state: present

    # ----------------------------------------------------
    - name: 3. 啟動容器 (docker-compose up)
      command: docker-compose -f "{{ playbook_dir }}/../docker/script/docker-compose.yaml" up -d
      args:
        chdir: "{{ playbook_dir }}/../docker/script"

    # ----------------------------------------------------
    - name: 4. 驗證容器狀態
      command: docker ps
      register: docker_ps
      changed_when: false

    - debug:
        var: docker_ps.stdout